server:
  port: 10000

spring:
  cloud:
    gateway:
      routes:
        - id: User-Service
          uri: lb://User-Service  #Since we are using client name so lb//User-Service is used. lb stands for load balancer. If we use host and port then http://127.0.0.1:9000
          predicates:
            - Path=/user/**    #If we have multiple paths then we separate it with a comma.
        - id: Rating-Service
          uri: lb://Rating-Service
          predicates:
            - Path=/rating/**
        - id: Hotel-Service
          uri: lb://Hotel-Service
          predicates:
            - Path=/hotel/**
  application:
    name: API-Gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/


# Okta Configuration for API gateway
okta:
  oauth2:
    issuer: https://dev-38772320.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa96oe1966FHiBXr5d7
    client-secret: PFsxOXsnGuSXsOs4_NB2aNZD9XC8mGgxnchOKeEs
    scopes: openid, profile, email, offline_access