server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: Anshuman007
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
    show-sql: true

  application:
    name: User-Service

#Security client configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-38772320.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal #calls different services internally
            client-id: 0oa96oe1966FHiBXr5d7
            client-secret: PFsxOXsnGuSXsOs4_NB2aNZD9XC8mGgxnchOKeEs
        provider:
          okta:
            issuer-uri: https://dev-38772320.okta.com/oauth2/default


eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

#These are by default true
    fetch-registry: true
    register-with-eureka: true


#Actuator
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,beans # * includes all the endpoints of the actuator.
        #exclude: loggers #This is used to exclude an endpoint of the actuator
  endpoint:
    health:
      show-details: always

#Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumeBufferSize: 10
        failureRateThreshold: 60 #percentage
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelRetry:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      ratingHotelBreaker:
        limitForPeriod: 2
        limitRefreshPeriod: 4s
        timeoutDuration: 0s
        registerHealthIndicator: true


#Okta Configuration
okta:
  oauth2:
    issuer: https://dev-38772320.okta.com/oauth2/default
    audience: api://default
